const assert = require('node:assert/strict');
const {Miniflare,convertV4MiniflareOptions}=require('miniflare');
const {build}=require('esbuild');
const {createHmac,randomUUID}=require('node:crypto');
(async()=>{
  const bundle=await build({entryPoints:['api-test/worker.js'],bundle:true,format:'esm',write:false});
  const secret='local-packing-test-secret-only';
  const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"packing-test",modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-08-10',bindings:{ENVIRONMENT:'test',FORGE_SESSION_SECRET:secret},d1Databases:['DB']}]}));
  try {
    const db=await mf.getD1Database('DB');
    await db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT,name TEXT,role TEXT,active INTEGER);
CREATE TABLE products(sku TEXT PRIMARY KEY,name TEXT,product_type TEXT,active INTEGER);
CREATE TABLE forge_operational_state(state_key TEXT PRIMARY KEY,json_value TEXT,updated_at TEXT,updated_by TEXT);
CREATE TABLE consumables(key TEXT PRIMARY KEY,name TEXT,stock INTEGER,reorder_level INTEGER,unit TEXT,updated_at TEXT);
CREATE TABLE consumable_history(id TEXT PRIMARY KEY,key TEXT,name TEXT,change_qty INTEGER,movement_type TEXT,reason TEXT,created_at TEXT,created_by TEXT);
INSERT INTO users VALUES('test-packer','local@example.test','Test Packer','packing',1);
INSERT INTO users VALUES('test-retail','retail@example.test','Test Retail','retail_staff',1);
INSERT INTO products VALUES('PLA001','Test Fox','pal',1);
INSERT INTO products VALUES('PLA002','Test Otter','pal',1);`);
    const initial={assembled:{PLA001:30,PLA002:20},inserts:{PLA001:{ready:30},PLA002:{ready:20}},finishedStock:{boat:{},cornwall:{},warehouse:{}},stock:{},transfers:[],packingHistory:[]};
    await db.prepare("INSERT INTO forge_operational_state VALUES('production',?,'initial','test')").bind(JSON.stringify(initial)).run();
    for(const key of ['clear_boxes','bottom_cards','stickers'])await db.prepare('INSERT INTO consumables VALUES(?,?,50,5,?,?)').bind(key,key,'units','initial').run();
    const token=uid=>{const p=Buffer.from(JSON.stringify({uid,exp:Date.now()+3600000})).toString('base64url');return p+'.'+createHmac('sha256',secret).update(p).digest('base64url');};
    async function call(path,body,auth=token('test-packer')) {const r=await mf.dispatchFetch('http://localhost'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+auth,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};}
    assert.equal((await call('/packing/batch',null,'')).status,401);
    assert.equal((await call('/packing/batch',null,token('test-retail'))).status,403);
    assert.equal((await call('/packing/batch')).status,200);
    const batch_id=randomUUID();
    assert.equal((await call('/packing/batch/start',{request_id:batch_id,quantity:40})).status,200);
    assert.equal((await call('/packing/batch/start',{request_id:randomUUID(),quantity:4})).status,409);
    const a={batch_id,request_id:randomUUID(),sku:'PLA001',quantity:15,destination:'boat'};
    assert.equal((await call('/packing/allocate',a)).status,409);
    assert.equal((await call('/packing/batch/step',{batch_id,step:3})).status,409);
    for(let step=1;step<=6;step++)assert.equal((await call('/packing/batch/step',{batch_id,step})).status,200);
    assert.equal((await call('/packing/allocate',{...a,request_id:randomUUID(),quantity:31})).status,409);
    await db.prepare("UPDATE consumables SET stock=0 WHERE key='stickers'").run();
    assert.equal((await call('/packing/allocate',a)).status,409);
    await db.prepare("UPDATE consumables SET stock=50 WHERE key='stickers'").run();
    await db.exec("CREATE TRIGGER test_rollback BEFORE INSERT ON consumable_history WHEN NEW.key='stickers' BEGIN SELECT RAISE(ABORT,'forced local test failure'); END;");
    assert.equal((await call('/packing/allocate',a)).status,500);
    assert.equal((await db.prepare("SELECT stock FROM consumables WHERE key='clear_boxes'").first()).stock,50);
    assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM packing_allocations').first()).n,0);
    assert.equal(JSON.parse((await db.prepare("SELECT json_value FROM forge_operational_state WHERE state_key='production'").first()).json_value).assembled.PLA001,30);
    await db.exec('DROP TRIGGER test_rollback;');
    const first=await call('/packing/allocate',a);assert.equal(first.status,200,JSON.stringify(first));
    assert.equal(first.body.state.finishedStock.boat.PLA001,15);
    assert.equal(first.body.state.assembled.PLA001,15);
    assert.equal((await call('/packing/allocate',a)).body.already_recorded,true);
    assert.equal((await call('/packing/allocate',{...a,quantity:1})).status,409);
    for(const quantity of [0,-1,1.5,10001])assert.equal((await call('/packing/allocate',{...a,request_id:randomUUID(),quantity})).status,400);
    assert.equal((await call('/packing/allocate',{...a,request_id:randomUUID(),destination:'invalid'})).status,400);
    assert.equal((await call('/packing/allocate',{...a,request_id:randomUUID(),sku:'UNKNOWN'})).status,400);
    const wh=await call('/packing/allocate',{...a,request_id:randomUUID(),quantity:10,destination:'warehouse'});
    assert.equal(wh.status,200);assert.equal(wh.body.state.finishedStock.warehouse.PLA001,10);
    const corn=await call('/packing/allocate',{...a,request_id:randomUUID(),sku:'PLA002',quantity:15,destination:'cornwall'});
    assert.equal(corn.status,200);assert.equal(corn.body.batch,null);
    assert.equal(corn.body.state.finishedStock.cornwall.PLA002,undefined);
    assert.equal(corn.body.state.transfers.at(-1).status,'awaiting_delivery');
    assert.equal(corn.body.state.consumables.stickers.stock,10);
    assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM consumable_history').first()).n,9);
    const batch2=randomUUID();await call('/packing/batch/start',{request_id:batch2,quantity:10});
    for(let step=1;step<=6;step++)await call('/packing/batch/step',{batch_id:batch2,step});
    // Two operators attempt to use the same five remaining Pals concurrently.
    const attempts=await Promise.all([1,2].map(()=>call('/packing/allocate',{batch_id:batch2,request_id:randomUUID(),sku:'PLA001',quantity:5,destination:'warehouse'})));
    assert.deepEqual(attempts.map(x=>x.status).sort(),[200,409]);
    const end=(await call('/packing/batch')).body;
    assert.equal(end.state.assembled.PLA001,0);assert.equal(end.state.consumables.clear_boxes.stock,5);
    assert.equal(end.batch.allocated,5);
    // The same request arriving concurrently still makes exactly one movement.
    const same={batch_id:batch2,request_id:randomUUID(),sku:'PLA002',quantity:5,destination:'boat'};
    const dup=await Promise.all([call('/packing/allocate',same),call('/packing/allocate',same)]);
    assert.deepEqual(dup.map(x=>x.status),[200,200]);
    const final=(await call('/packing/batch')).body;
    assert.equal(final.state.finishedStock.boat.PLA002,5);assert.equal(final.state.consumables.clear_boxes.stock,0);assert.equal(final.batch,null);
    console.log('PASS: authenticated packing role, all six steps, mixed 40-box split, Boat/Warehouse stock, Cornwall awaiting delivery, validation, restart persistence, duplicate retries, concurrent stock protection and atomic material deductions.');
    await require('./transfers.test.cjs').checkTransfers(mf,db,token);
    if(process.env.TRANSFER_UI_SERVER)await require('./transfers-preview.cjs').startPreview(mf,db,token('test-admin'));
    if(process.env.PACKING_UI_TEST)await require('./mixed-packing-ui.cjs').checkUI(mf,db,token('test-packer'),initial);
  }finally{await mf.dispose();}
})().catch(e=>{console.error(e);process.exitCode=1;});
