const { readFileSync } = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = readFileSync('assets/forge.js', 'utf8');
const context = vm.createContext({});
vm.runInContext(source.slice(source.indexOf('function packingKpiSummary('), source.indexOf('function renderPackingKpis(')), context);
const summary = context.packingKpiSummary;
const pals = [{sku:'A'}, {sku:'B'}];
const stock = {assembled:{A:12,B:10}, inserts:{A:{ready:8}, B:{ready:10}}, consumables:{clear_boxes:{stock:64}, stickers:{stock:92}, bottom_cards:{stock:37}}};
assert.equal(summary(stock,pals).palsReady,18);
assert.equal(summary(stock,pals).capacity,18);
stock.consumables.stickers.stock=12;
assert.equal(summary(stock,pals).capacity,12);
assert.equal(summary(stock,[...pals,pals[0]]).palsReady,18);
stock.inserts.A.ready=0;
assert.equal(summary(stock,pals).capacity,10);
stock.consumables.clear_boxes.stock=0;
assert.equal(summary(stock,pals).capacity,0);
assert.equal(summary({},pals).capacity,0);
assert.equal(summary({assemblyStock:{A:5},inserts:{A:{ready:3}}},pals).palsReady,3);
assert.equal(summary({assembled:{A:0},assemblyStock:{A:5},inserts:{A:{ready:3}}},pals).palsReady,0);
stock.consumables.clear_boxes.stock='invalid';
assert.equal(summary(stock,pals).capacity,0);
// Completing a batch reduces both eligible stock and shared packaging capacity.
stock.consumables.clear_boxes.stock=64;
stock.assembled.B=6;
stock.inserts.B.ready=6;
stock.consumables.stickers.stock=8;
assert.equal(summary(stock,pals).capacity,6);
console.log('Packing KPI checks passed: quantities, inserts, shared supplies, zero stock, legacy stock, duplicate SKUs, invalid values, and completed batches.');
